"""fix nullable operador_saida and data_saida

Revision ID: 7d6bd14883c8
Revises: 8839fe3aa243
Create Date: 2026-03-10 15:16:50.963983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6bd14883c8'
down_revision = '8839fe3aa243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_pessoa', schema=None) as batch_op:
        batch_op.alter_column('operador_saida_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('data_saida',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_pessoa', schema=None) as batch_op:
        batch_op.alter_column('data_saida',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('operador_saida_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
