"""alter movimentacao pessoa

Revision ID: 8839fe3aa243
Revises: 26c91841a271
Create Date: 2026-03-04 15:57:27.724127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8839fe3aa243'
down_revision = '26c91841a271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('operador_entrada_id', sa.Integer(), nullable=False),
    sa.Column('operador_saida_id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['operador_entrada_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['operador_saida_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_pessoa')
    # ### end Alembic commands ###
