"""fiz fk

Revision ID: 935c1278e865
Revises: 
Create Date: 2026-02-17 15:13:12.615742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935c1278e865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('movimentacoes_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('operador_saida_id', sa.Integer(), nullable=False),
    sa.Column('operador_retorno_id', sa.Integer(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('km_saida', sa.Integer(), nullable=False),
    sa.Column('data_retorno', sa.DateTime(), nullable=True),
    sa.Column('km_retorno', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['operador_retorno_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['operador_saida_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_veiculo')
    op.drop_table('veiculos')
    op.drop_table('pessoa')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('setores')
    # ### end Alembic commands ###
